movies/movieapp/urls.py
from django.urls import path

from . import views

app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movies/movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

movies/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name= models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movies/movieapp/forms.py
from django import forms
from .models import Movie

class Movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name',
                'desc',
                'year',
                'img']

movies/movieapp/views.py
from django.shortcuts import render,redirect
from django.shortcuts import HttpResponse
from .models import Movie
from .forms import Movieform

def index(request):
    movie=Movie.objects.all
    context={
        'movie_list':movie
    }
    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie= Movie.objects.get(id=id)
    form=Movieform(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')


    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')



    return render(request,'delete.html')





# Create your views here.

movies/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="enter movie name">
        <input type="text" name="desc" placeholder="enter movie description">
        <input type="text" name="year" placeholder="enter movie year">
        <input type="file" name="img">
        <input type="submit">


</form>
{% endblock %}

movies/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        Online Movie store
    </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movies/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure???
    <input type="submit">
    <a href="{% url 'movieapp:index' %}" class="btn btn-info">cancel</a>
</form>

movies/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <img src="{{movie.img.url}}" height="400" width="600">
        </div>
<div class="col-md-6">
    <h2>{{movie.name}}</h2>
    <H4>{{movie.desc}}</H4>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
</div>


    </div>
</div>
{% endblock %}

movies/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<!--    -->
    {{form.as_p}}
<!--    <form>-->
<!--        <input name="name" type="text" placeholder="name"><br>-->
<!--        <input name="desc" type="text" placeholder="description"><br>-->
<!--        <input name="year" type="number" placeholder="year"><br>-->
<!--        <input type="image">-->
<!--    </form>-->

    <input type="submit">
</form>

movies/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Select</a>
  </div>


</div>
        </div>
        {% endfor %}
    </div>

</div>
<div align="center">
      <a href="{% url 'movieapp:add_movie' %}" class="btn btn-warning" >add</a>

</div>



{% endblock %}